const { AccountCreatedPage } = require("../../pages/account_created_page");
const { CartPage } = require("../../pages/cart_page");
const { CheckoutPage } = require("../../pages/checkout_page");
const { ContactUsPage } = require("../../pages/contact_us_page");
const { HomePage } = require("../../pages/home_page");
const { LoginPage } = require("../../pages/login_page");
const { PaymentPage } = require("../../pages/payment_page");
const { ProductPage } = require("../../pages/product_page");
const { SignupPage } = require("../../pages/signup_page");

const loginPage = new LoginPage()
const homePage = new HomePage()
const productPage = new ProductPage()
const cartPage = new CartPage()
const checkoutPage = new CheckoutPage()
const paymentPage = new PaymentPage()
const contactUsPage = new ContactUsPage()
const signupPage = new SignupPage()
const accountCreatedPage = new AccountCreatedPage()

let data

describe("E2E Test Suite", ()=>{

    //get json data to use in each test.
    before(()=>{
        cy.fixture("dataTest").then((jsonData)=>{
            data = jsonData;
        })
    })

    //open url before to start each test.
    beforeEach(()=>{
        loginPage.navigate('https://automationexercise.com/')
        loginPage.validateUrl();
    })

    it('Product list', function(){
        homePage.goToCenterPage()
        homePage.validateHomePage()
    })

    it('Chose product', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.validateProductPage()
    })

    it('Set quantity product', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.validateProductQuantity(data.quantity)
    })

    it('Add product to cart', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.addToCart()
        productPage.validateProductAddedToCart()
    })

    it('View cart', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.validateCartPage()
    })

    it('Go to checkout process', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.validateRegisterLoginWindow()
    })

    it('Register login', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        loginPage.validateLoginPage()
    })

    it('Signup user', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(data.quantity)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.validateSignupPage()
    })

    it('Create new account', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.validateAccountCreated()
    })

    it('Continue after account created', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.validateHomePage()
    })

    it('Go to cart view from header', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.validateCartPage()
    })

    it('Proceed to payment process already logged in', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.validateCheckoutPage()
    })

    it('Set a comment in the new order', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.validateOrderMessage(data.message)
    })

    it('Place order', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.validatePaymentPage()
    })

    it('Pay and confirm order', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.validateOrderPlaced()
    })

    it('Continue after pay the order', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.validateHomePage()
    })

    it('Close session from the home page', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.logout()
        loginPage.validateLoginPage()
    })

    it('Login', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.logout()
        loginPage.enterUserEmail(email)
        loginPage.enterUserPassword(data.password)
        loginPage.singIn();
        homePage.validateHomePage();
    })

    it('Go to contact us page', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.logout()
        loginPage.enterUserEmail(email)
        loginPage.enterUserPassword(data.password)
        loginPage.singIn()
        homePage.contactUs()
        contactUsPage.validateContactUsPage()
    })

    it('Send contact us form', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.logout()
        loginPage.enterUserEmail(email)
        loginPage.enterUserPassword(data.password)
        loginPage.singIn()
        homePage.contactUs()
        contactUsPage.contactForm(data.name, data.email, data.subject, data.message)
        contactUsPage.validateContactUsSubmitted()
    })

    it('Close session from the contact us page', function(){
        homePage.goToCenterPage()
        homePage.choseFirstProduct()
        productPage.setQuantity(30)
        productPage.addToCart()
        productPage.viewCart()
        cartPage.checkout()
        cartPage.registerLogin()
        var email = data.email.replace("-", Math.floor(Math.random() * 10000))
        loginPage.registerUser(data.name, email)
        loginPage.signup()
        signupPage.createAccount(data)
        accountCreatedPage.continue()
        homePage.viewCart()
        cartPage.checkout()
        checkoutPage.orderComment(data.message)
        checkoutPage.placeOrder()
        paymentPage.payAndConfirmOrder(data)
        paymentPage.continue()
        homePage.logout()
        loginPage.enterUserEmail(email)
        loginPage.enterUserPassword(data.password)
        loginPage.singIn()
        homePage.contactUs()
        contactUsPage.contactForm(data.name, data.email, data.subject, data.message)
        contactUsPage.logout()
        loginPage.validateLoginPage()
    })
})